/* This file was generated by lv6 version master.736 (a07e17b8b31c25b6c40eb5e56168e6b07a5f9794). */
/*  lv6 data_average.lus -n accumulate -2c */
/* on 81cd4c0b6a4e the 09/11/2018 at 07:38:32 */

#include <stdlib.h>
#include <string.h>

#include "lustre_types.h"
#include "lustre_consts.h"

#ifndef _data_average_accumulate_H_FILE
#define _data_average_accumulate_H_FILE
void data_average_accumulate_step(_boolean ,_real ,_real ,_real *);

/////////////////////////////////////////////////
#endif
