/* This file was generated by lv6 version master.736 (a07e17b8b31c25b6c40eb5e56168e6b07a5f9794). */
/*  lv6 data_average.lus -n division -2c */
/* on 81cd4c0b6a4e the 09/11/2018 at 07:38:32 */
#include "data_average_division.h"
//// Defining step functions
// Step function(s) for Lustre_slash_ctx
void Lustre_slash_step(_real i1,_real i2,_real *out){
  *out = (i1 / i2);

} // End of Lustre_slash_step

// Step function(s) for data_average_division_ctx
void data_average_division_step(_boolean verify,_real num,_real sum,_real *avg){
   _real _split_1;

  Lustre_slash_step(sum,num,&_split_1); 
   if (verify == _true) {
     *avg = _split_1;
   } else {
     *avg = 0.0;
   }

} // End of data_average_division_step

