/* This file was generated by lv6 version master.736 (a07e17b8b31c25b6c40eb5e56168e6b07a5f9794). */
/*  lv6 data_average.lus -n accumulate -2c */
/* on 81cd4c0b6a4e the 09/11/2018 at 07:38:32 */
#include "data_average_accumulate.h"
//// Defining step functions
// Step function(s) for data_average_accumulate_ctx
void data_average_accumulate_step(_boolean verify,_real A,_real B,_real *sum){
   _real _split_1;

  _split_1 = A + B;
   if (verify == _true) {
     *sum = _split_1;
   } else {
     *sum = 0.0;
   }

} // End of data_average_accumulate_step

