/* This file was generated by lv6 version master.736 (a07e17b8b31c25b6c40eb5e56168e6b07a5f9794). */
/*  lv6 data_average.lus -n division -2c */
/* on 81cd4c0b6a4e the 09/11/2018 at 07:38:32 */

#ifndef _SOC2C_PREDEF_TYPES
#define _SOC2C_PREDEF_TYPES
typedef int _boolean;
typedef int _integer;
typedef char* _string;
typedef double _real;
typedef double _double;
typedef float _float;
#define _false 0
#define _true 1
#endif
// end of _SOC2C_PREDEF_TYPES
// User typedef 
#ifndef _data_average_division_TYPES
#define _data_average_division_TYPES
#endif // enf of  _data_average_division_TYPES
// Memoryless soc ctx typedef 
// Memoryfull soc ctx typedef 
