/* This file was generated by lv6 version master.749 (493bc565c67740076667e4be85f84654493f204b). */
/*  lv6 data_average.lus -n accumulate -2c */
/* on 4b73288c91af the 21/11/2018 at 07:37:06 */
#include "data_average_accumulate.h"
//// Defining step functions
// Step function(s) for data_average_accumulate_ctx
void data_average_accumulate_step(_boolean verify,_real A,_real B,_real *sum){
   _real _split_1;

  _split_1 = A + B;
   if (verify == _true) {
     *sum = _split_1;
   } else {
     *sum = 0.0;
   }

} // End of data_average_accumulate_step

