/* This file was generated by lv6 version master.749 (493bc565c67740076667e4be85f84654493f204b). */
/*  lv6 data_average.lus -n accumulate -2c */
/* on 4b73288c91af the 21/11/2018 at 07:37:06 */

#include <stdlib.h>
#include <string.h>

#include "lustre_types.h"
#include "lustre_consts.h"

#ifndef _data_average_accumulate_H_FILE
#define _data_average_accumulate_H_FILE
void data_average_accumulate_step(_boolean ,_real ,_real ,_real *);

/////////////////////////////////////////////////
#endif
