/* This file was generated by lv6 version master.749 (493bc565c67740076667e4be85f84654493f204b). */
/*  lv6 data_average.lus -n division -2c */
/* on 4b73288c91af the 21/11/2018 at 07:37:06 */

#ifndef _SOC2C_PREDEF_TYPES
#define _SOC2C_PREDEF_TYPES
typedef int _boolean;
typedef int _integer;
typedef char* _string;
typedef double _real;
typedef double _double;
typedef float _float;
#define _false 0
#define _true 1
#endif
// end of _SOC2C_PREDEF_TYPES
// User typedef 
#ifndef _data_average_division_TYPES
#define _data_average_division_TYPES
#endif // enf of  _data_average_division_TYPES
// Memoryless soc ctx typedef 
// Memoryfull soc ctx typedef 
